[theme]
theme = "modern"
[icons]
icons = "awesome6"

[[block]]
block = "custom"
command = "echo '\uf085' `cat $HOME/config/settings/.current-profile`"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:3) "

[[block]]
block = "load"
interval = 1
format = " $icon $1m.eng(w:4) "

[[block]]
block = "net"
device = "enp5s0"
format = " $icon $ip "
interval = 5

[[block]]
block = "sound"
headphones_indicator = true

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%a %d-%m %T') "
