#!/usr/bin/zsh

# set monitor configuration
#xrandr --output DP-2 --auto --primary --output DP-0 --auto --right-of DP-2 --output HDMI-0 --auto --left-of DP-2
#xrandr --setmonitor 'MR' 1442/597x1920/336+5360+0 DP-0
xrandr --setmonitor 'MR' 1200/518x1680/324+5360+0 DP-0

# set mouse acceleration
xinput --set-prop 'Logitech Gaming Mouse G502' 'libinput Accel Speed' 0.7
