#!/usr/bin/zsh

# set monitor configuration
xrandr --output DP-2 --auto --primary --output DP-0 --auto --right-of DP-2 --output HDMI-0 --auto --left-of DP-2

# set mouse acceleration
xinput --set-prop 'Logitech Gaming Mouse G502' 'libinput Accel Speed' 0.7

